"""add session_token to user

Revision ID: c9f73801ffec
Revises: 80439d55cab6
Create Date: 2025-06-02 20:22:51.169340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9f73801ffec'
down_revision: Union[str, None] = '80439d55cab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('session_token', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_session_token'), 'users', ['session_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_session_token'), table_name='users')
    op.drop_column('users', 'session_token')
    # ### end Alembic commands ###
