"""remove user-youtube_transcript relationship

Revision ID: ea5a9e9b58d0
Revises: c9f73801ffec
Create Date: 2025-06-02 20:25:15.213416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea5a9e9b58d0'
down_revision: Union[str, None] = 'c9f73801ffec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('youtube_transcripts_user_id_fkey'), 'youtube_transcripts', type_='foreignkey')
    op.drop_column('youtube_transcripts', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('youtube_transcripts', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('youtube_transcripts_user_id_fkey'), 'youtube_transcripts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
